### ISSUE TITLE
Could a formula break the import for population_at_risk for LF for ONLY Indonesia

### ISSUE THREAD

**Issue by apavluck** [ICTatRTI/USAID_NTD_Database#8]
The M&E team discovered the other day that the population_at_risk for LF for ONLY Indonesia is wrong and shows total population rather than the appropriate population at risk value for LF from the workbooks. I looked at the reporting tables — it is wrong. I looked at the submission tables — it is wrong. I asked Russell to pull the workbook and sure enough — the data is blank where it should be blank and filled in where it should be filled in. HOWEVER, there is a formula in the cells that the national program must have added. The formula, if it evaluated to true, would copy the total population and present the erroneous data we are seeing. However, that is not happening in the workbooks. Can you tell if the submission process might be effected by this formula?

I sent the spreadsheet and highlighted the cell we are talking about on the LF tab via email

**Comment by apavluck** [comment]
select country,region_desc, workbook_year, disease, total_pop, population_at_risk  from reporting_diseases
where country = "indonesia" and region_desc = "Bali" and disease="lf"

Here you can see it. For Bali, according to the 2015 workbook, for LF there is no population at risk

**Comment by tjmuehleman** [comment]
This appears to be an issue isolated to the IF(OR excel function. I was unable to recreate the issue with a simple IF formula. Furthermore, I've read a number of articles that describe similar behavior with the IF(OR function.
